version: '3'

services:

  nginx:
    container_name: transatcions-nginx
    build: docker/nginx
    links:
      - php
    ports:
      - 80:80
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app

  php:
    container_name: transatcions-php
    build: docker/php
    links:
      - postgres
    environment:
      PGPASSWORD: postgres
    working_dir: /var/www/app
    volumes:
      - ./:/var/www/app

  postgres:
    container_name: transatcions-postgres
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: transatcions
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database/data:/var/lib/postgresql/data

